version: '3'

services:
  db:
    image: arangodb/arangodb
    environment:
      ARANGO_ROOT_PASSWORD: '123456'
    command: 
      - "arangod"
      - "server.endpoint tcp://0.0.0.0:8529"
    restart: always
    ports:
      - '8529:8529'
    volumes:
      - arango_data:/var/lib/arangodb3

volumes:
  arango_data: